name: 'Terraform apply'
description: 'Running Terraform apply'

inputs:
  WORKING_DIRECTORY:
    description: 'directory where the tf code is'
    required: false
    default: './infra-base/terraform'
runs:
  using: "composite"
  steps:
    - id: 'install-terraform'
      uses: hashicorp/setup-terraform@v2
      with: 
        terraform_version: '${{ env.TERRAFORM_VERSION }}'
    - name: Download Artifact
      id: download-tf-plan
      uses: actions/download-artifact@v3
      with:
        name: tf-plan
        path: '${{ github.workspace }}/infra/terraform/'
    - name: terraform init
      id: 'tf-init'
      run: |
           BUCKET_NAME="${{ env.PROJECT_NAME }}-tf-state-lock-${{ env.ENVIRONMENT }}-${{ env.AWS_REGION }}" 
           DYNAMODB_TABLE="${{ env.PROJECT_NAME }}-tf-state-${{ env.ENVIRONMENT }}-${{ env.AWS_REGION }}"
           terraform init \
           -backend-config=bucket="$BUCKET_NAME" \
           -backend-config=region='${{ env.AWS_REGION }}' \
           -backend-config=key='state' \
           -backend-config=dynamodb_table="$DYNAMODB_TABLE"
      shell: bash
      working-directory: '.${{ inputs.WORKING_DIRECTORY }}'
    - name: terraform destroy
      id: tf-destroy
      run: |
            terraform destroy \
            -var 'region=${{ env.AWS_REGION }}' \
            -var 'environment=${{ env.ENVIRONMENT }}' 
      shell: bash
      working-directory: '.${{ inputs.WORKING_DIRECTORY }}'