name: 'Terraform apply'
description: 'Running Terraform apply'

inputs:
  WORKING_DIRECTORY:
    description: 'directory where the tf code is'
    required: false
    default: '/infra-base/terraform'
  PATH_FLUX_REPO:
    description: ' GH token to push file to repo where manifest will be stored'
    required: true
    default: 'empty'

runs:
  using: "composite"
  steps:
    - name: Terraform install
      id: 'install-terraform'
      uses: hashicorp/setup-terraform@v2
      with: 
        terraform_version: '${{ env.TERRAFORM_VERSION }}'
    - name: Validate terraform version
      id: validate-tf-version
      run: terraform version
      shell: bash
    - name: Download Artifact
      id: download-tf-plan
      uses: actions/download-artifact@v3
      with:
        name: tf-plan
        path: '${{ github.workspace }}${{ inputs.WORKING_DIRECTORY }}'
    - name: Run terraform init
      id: 'tf-init'
      run: |
           BUCKET_NAME="${{ env.PROJECT_NAME }}-tf-state-lock-${{ env.ENVIRONMENT }}-${{ env.AWS_REGION }}" 
           DYNAMODB_TABLE="${{ env.PROJECT_NAME }}-tf-state-${{ env.ENVIRONMENT }}-${{ env.AWS_REGION }}"
           terraform init \
           -backend-config=bucket="$BUCKET_NAME" \
           -backend-config=region='${{ env.AWS_REGION }}' \
           -backend-config=key='state' \
           -backend-config=dynamodb_table="$DYNAMODB_TABLE"
      shell: bash
      working-directory: '.${{ inputs.WORKING_DIRECTORY }}'
    - name: Run terraform apply
      run: |
           terraform apply \
           -input=false \
           ${{ github.run_id }}.tfplan
      shell: bash
      env:
          GITHUB_TOKEN: '${{ inputs.PATH_FLUX_REPO }}'
      working-directory: '.${{ inputs.WORKING_DIRECTORY }}'