# This is a basic workflow to help you get started with Actions
name: terraform deploy template
# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      PROJECT_NAME:
        required: true
        type: string
      TERRAFORM_VERSION:
        required: false
        type: string
        default: '1.4.6'
    secrets: 
      AWS_ACCOUNT_NUMBER:
        required: true

env:
  ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
  AWS_REGION: ${{ inputs.AWS_REGION }}
  PROJECT_NAME: ${{ inputs.PROJECT_NAME }}
  TERRAFORM_VERSION: ${{ inputs.TERRAFORM_VERSION }}

jobs:
  set-up-terraform-backend:
    runs-on: ubuntu-latest
    steps:  
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/GithubActions-smart-cash-crossplane'
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: config tf backend
        id: tf-backend
        run: ./terraform-backend.sh
        working-directory: .github/jobs/

  terraform-plan:
    runs-on: ubuntu-latest
    needs: set-up-terraform-backend
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/GithubActions-smart-cash-crossplane'
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: terraform plan
        id: terraform-plan
        uses: ./.github/actions/terraform-plan
        with:
          WORKING_DIRECTORY: '/infra-base/terraform'
  terraform-apply:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: terraform-plan
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/GithubActions-smart-cash-crossplane'
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: terraform apply
        id: tf-apply
        uses: ./.github/actions/terraform-apply
        with:
          WORKING_DIRECTORY: '/infra-base/terraform'
  install-argocd:
    runs-on: ubuntu-latest
    needs: terraform-apply
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/GithubActions-smart-cash-crossplane'
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: get eks creds
        run: |
                aws eks update-kubeconfig --name '${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT }}' --region '${{ env.AWS_REGION }}'
      - name: install argocd 
        run: |
            kubectl create namespace argocd
            kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml     

